# -*- mode:toml; -*-
[module.arch-ihk]
    # pseudo modules and so on that are assumed as available
    provides = [
      "tag/cpu/amd64",
      "tag/cpu/pause",
      "tag/cpu/clflush",
      "tag/cpu/xapic",
      "tag/cpu/amd64ioapic",
      "tag/mode/kernel",
      "tag/platform/pc",
      "tag/compiler/gcc",
      "tag/boot/ihk",
      "tag/boot/multiboot",
      "tag/cap/spinning",
      ]

    requires = [
      "tag/platform/ihk",
      "boot64.elf",
      "Makefile",
      ]
