# -*- mode:toml; -*-
[module.arch-amd64]
    # pseudo modules and so on that are assumed as available
    noauto = true
    provides = [
      "tag/cpu/amd64",
      "tag/cpu/pause",
      "tag/cpu/clflush",
      "tag/cpu/xapic",
      "tag/cpu/amd64ioapic",
      "tag/mode/kernel",
      "tag/platform/pc",
      "tag/compiler/gcc",
      "tag/boot/acpi",
      "tag/boot/multiboot",
      "tag/cap/spinning",
      ]

    requires = [
      "boot32.elf",
      "tag/emu-qemu",
      "tag/emu-bochs",
      "Makefile",
      ]
