# -*- mode:toml; -*-
[module.cxxabi-app]
    appfiles = [ "runtime/cxxsupport.cc", "runtime/string.cc", "runtime/cxxdelete.cc" ]
    provides = [ "vector", "queue", "functional", "pthread.h", "endian.h" ]
    makefile_head = '''
APP_CPPFLAGS += -nostdinc -nostdinc++ -isystem ${vars.cxx_path}/include/c++/v1 -isystem ${vars.cxx_path}/include 
APP_LDFLAGS += -Wl,--eh-frame-hdr --sysroot=${vars.cxx_path}/../
APP_LIBS += -lc++ -lc++abi -lunwind -lgcc
'''
