# -*- mode:toml; -*-
[module.cxxabi-app]
    incfiles = [ "runtime/futex.hh" ]
    appfiles = [ "runtime/cxxsupport.cc", "runtime/pthread.cc", "runtime/futex.cc" ]
    provides = [ 
      "tag/libc", "tag/libcxx",
      "iostream", "vector", "queue", "functional",  "bits/alltypes.h", "endian.h"
    ]
    makefile_head = '''
APP_CPPFLAGS += -nostdinc -nostdinc++ -isystem ${vars.cxx_path}/include/c++/v1 -isystem ${vars.cxx_path}/include 
APP_LDFLAGS += -Wl,--eh-frame-hdr --sysroot=${vars.cxx_path}/../
APP_LIBS += ${vars.cxx_path}/lib/libomp.a ${vars.cxx_path}/lib/libc++.a ${vars.cxx_path}/lib/libc++abi.a ${vars.cxx_path}/lib/libunwind.a ${vars.cxx_path}/lib/libc.a -lgcc
'''
