# -*- mode:toml; -*-
[module.app-init-smd]
    crtfiles = [ "app/start.S", "app/crtend.S", "app/crtbegin.cc" ]
    initappfiles = [ "app/init.cc" ]
    provides = [ "app/init.elf" ]
    requires = [ "runtime/cxxsupport.cc", "runtime/DebugSink.cc" ]
    makefile_head = '''
TARGETS += app/init.elf

# disable features which might require runtime support we don't have
APP_CXXFLAGS += -fno-exceptions -fno-rtti -fno-stack-protector
CRT_CXX = $(APP_CXX)
CRT_AS = $(APP_AS)
CRT_CXXFLAGS = $(APP_CXXFLAGS)
CRT_CPPFLAGS = $(APP_CPPFLAGS)
INITAPP_CXX = $(APP_CXX)
INITAPP_AS = $(APP_AS)
INITAPP_CXXFLAGS = $(APP_CXXFLAGS)
INITAPP_CPPFLAGS = $(APP_CPPFLAGS)
'''
    makefile_body = '''
app/init.elf: $(INITAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ app/start.o app/crtbegin.o -lgcc $(INITAPPFILES_OBJ) $(APPFILES_OBJ) app/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > init.sym
	$(OBJDUMP) -dS $@ | c++filt > init.disasm
	$(STRIP) $@
'''
