# -*- mode:toml; -*-
[module.app-common]
    crtfiles = [ "runtime/start.S", "runtime/crtend.S", "runtime/crtbegin.cc" ]
    provides = [ "crtbegin" ]
    requires = [ "runtime/cxxsupport.cc", "runtime/DebugSink.cc" ]

    makefile_head = '''
# disable features which might require runtime support we don't have
APP_CXXFLAGS += -fno-exceptions -fno-rtti

INITAPP_CXX = $(APP_CXX)
INITAPP_AS = $(APP_AS)
INITAPP_CXXFLAGS = $(APP_CXXFLAGS)
INITAPP_CPPFLAGS = $(APP_CPPFLAGS)
INITAPP_CXXFLAGS += -fno-stack-protector

CRT_CXX = $(APP_CXX)
CRT_AS = $(APP_AS)
CRT_CXXFLAGS = $(APP_CXXFLAGS)
CRT_CPPFLAGS = $(APP_CPPFLAGS)
CRT_CXXFLAGS += -fno-stack-protector
'''
