# -*- mode:toml; -*-
[module.app-process-test]
    initappfiles = [ "app/images.S" ]
    processtestappfiles = [ "process_test/process_test.cc", "process_test/mlog.cc" ]
    requires = [ "crtbegin"]
    provides = [ "app-process-test" ]

    makefile_head = '''
TARGETS += process_test/process_test.elf
PROCESSTESTAPP_CXX ?= $(APP_CXX)
PROCESSTESTAPP_AS ?= $(APP_AS)
PROCESSTESTAPP_CXXFLAGS += $(APP_CXXFLAGS)
PROCESSTESTAPP_CPPFLAGS += $(APP_CPPFLAGS)
PROCESSTESTAPP_CXXFLAGS += -fno-stack-protector
PROCESSTESTAPP_ASFLAGS += $(APP_ASFLAGS)
APP_IMAGES = process_test/process_test.elf
'''

    makefile_body = '''
app/images.o: $(APP_IMAGES)

process_test/process_test.elf: $(PROCESSTESTAPPFILES_OBJ) $(APPFILES_OBJ) $(CRTFILES_OBJ)
	$(APP_CXX) $(APP_LDFLAGS) $(APP_CXXFLAGS) -nostdlib -o $@ runtime/start.o runtime/crtbegin.o $(PROCESSTESTAPPFILES_OBJ) $(APPFILES_OBJ) $(APP_LIBS) runtime/crtend.o
	$(NM)  $@ | cut -d " " -f 1,3 | c++filt -t > process_test.sym
	$(OBJDUMP) -dS $@ | c++filt > process_test.disasm
	$(STRIP) $@
'''

