#pragma once

#warning C++11 include test included, may lead to excessive compilation times

#include <cstdlib>
#include<csignal>
#include<csetjmp>
#include<cstdarg>
//#include<typeinfo>
//#include<typeindex>
#include<type_traits>
#include<bitset>
#include<functional>
#include<utility>
#include<ctime>
#include<chrono>
#include<cstddef>
#include<initializer_list>
#include<tuple>
#include<new>
#include<memory>
#include<scoped_allocator>
#include<climits>
#include<cfloat>
#include<cstdint>
#include<cinttypes>
#include<limits>
#include<exception>
#include<stdexcept>
#include<cassert>
#include<system_error>
#include<cerrno>
#include<cctype>
#include<cwctype>
#include<cstring>
#include<cwchar>
//#include<cuchar>
#include<string>
#include<array>
#include<vector>
#include<deque>
#include<list>
#include<forward_list>
#include<set>
#include<map>
#include<unordered_set>
#include<unordered_map>
#include<stack>
#include<queue>
#include<iterator>
#include<algorithm>
#include<cmath>
#include<complex>
#include<valarray>
#include<random>
#include<numeric>
#include<ratio>
#include<cfenv>
#include<locale>
#include<clocale>
#include<codecvt>
#include<iosfwd>
#include<ios>
#include<istream>
#include<ostream>
#include<iostream>
#include<fstream>
#include<sstream>
#include<iomanip>
#include<streambuf>
#include<cstdio>
#include<regex>
#include<atomic>
#include<thread>
#include<mutex>
#include<future>
#include<condition_variable>
