# -*- mode:toml; -*-
[module.mythos-invocationBuffer]
    incfiles = [ "mythos/InvocationBuf.hh", "mythos/syscall.hh", "mythos/invocation.hh",
             "mythos/protocol/common.hh",
             "mythos/protocol/KernelObject.hh",
             "mythos/protocol/ExecutionContext.hh",
             "mythos/protocol/PageMap.hh",
             "mythos/protocol/Frame.hh",
             "mythos/protocol/KernelMemory.hh",
             "mythos/protocol/Example.hh",
             "mythos/protocol/CapMap.hh",
             "mythos/protocol/Portal.hh",
             "mythos/protocol/InterruptControl.hh",
             "mythos/protocol/PerfMon.hh",
             ]
