# -*- mode:toml; -*-
[module.objects-thread-team]
    incfiles = [ "objects/PerformanceMonitoring.hh", "objects/ProcessorAllocator.hh", "objects/ThreadTeam.hh", "mythos/protocol/ThreadTeam.hh", "objects/PluginThreadTeam.hh", "objects/ProcessorPool.hh", "objects/IProcessorPool.hh" ]
    kernelfiles = [ "objects/PerformanceMonitoring.cc", "objects/ProcessorAllocator.cc", "objects/ThreadTeam.cc", "objects/PluginThreadTeam.cc"]
